services:
  frontend:
    build:
      context: .
      target: dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app # bind mount the whole project — live code changes
      - /app/node_modules # anonymous volume (container only) — keeps container's node_modules
