name: 'Build and Push Docker Image'
description: 'Common setup steps for building and pushing Docker images'

inputs:
  docker-username:
    description: 'Docker username'
    required: true
  docker-token:
    description: 'Docker personal access token'
    required: true
  docker-repository:
    description: 'Name of Dockerhub repository'
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  push-latest:
    description: 'Whether to also tag the image as latest'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # Enable multi-platform builds within Docker workflows by installing QEMU static binaries.
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Create and boot a builder to be used in the following steps.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-token }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        context: '{{defaultContext}}'
        # ⚠️ The official docker/build-push-action uses the multiline format as its standard for multiple tags, not comma-separated.
        tags: |
          ${{ inputs.docker-repository }}:${{ inputs.image-tag }}
          ${{ inputs.push-latest == 'true' && format('{0}:latest', inputs.docker-repository) || '' }}
